DROP SCHEMA public CASCADE;

CREATE SCHEMA public;

CREATE TABLE time (
  id serial NOT NULL PRIMARY KEY,
  nome VARCHAR(45) NOT NULL
);

CREATE TABLE jogador (
  id serial NOT NULL PRIMARY KEY,
  nome VARCHAR(45) NOT NULL,
  idade int NOT NULL,
  time_id int NOT NULL,
  FOREIGN KEY(time_id) REFERENCES time(id)
  ON UPDATE CASCADE
  ON DELETE CASCADE
);
